"""Export a browser/server-consumable Sentinel policy JSON (+ optional TS embed)."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np

from iron_glove_rl.utils.contract import (
    FEATURE_ORDER,
    NORMALIZATION,
    OBSERVATION_VERSION,
    POLICY_VERSION,
)

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_JSON = ROOT.parent / "client" / "public" / "models" / "sentinel-policy.json"
DEFAULT_TS = ROOT.parent / "server" / "src" / "sentinelPolicyData.ts"


def sigmoid(x: np.ndarray) -> np.ndarray:
    return 1.0 / (1.0 + np.exp(-np.clip(x, -20.0, 20.0)))


def metadata(training_seed: int, kind: str, extra: dict | None = None) -> dict:
    meta = {
        "policyVersion": POLICY_VERSION,
        "observationVersion": OBSERVATION_VERSION,
        "featureOrder": list(FEATURE_ORDER),
        "normalization": dict(NORMALIZATION),
        "trainingSeed": int(training_seed),
        "kind": kind,
    }
    if extra:
        meta.update(extra)
    return meta


def heuristic_artifact(training_seed: int = 0) -> dict:
    return metadata(training_seed, "heuristic")


def export_sb3(model: Any, training_seed: int) -> dict:
    """Read PPO MlpPolicy weights. Stores torch Linear layouts (out, in)."""
    policy = model.policy
    state = {k: v.detach().cpu().numpy() for k, v in policy.state_dict().items()}
    layers = []
    idx = 0
    while f"mlp_extractor.policy_net.{idx}.weight" in state:
        w = state[f"mlp_extractor.policy_net.{idx}.weight"]
        b = state[f"mlp_extractor.policy_net.{idx}.bias"]
        layers.append({"w": w.tolist(), "b": b.tolist(), "act": "tanh"})
        idx += 2  # Linear, Tanh, Linear, Tanh, ...
    aw = state["action_net.weight"]
    ab = state["action_net.bias"]
    return metadata(
        training_seed,
        "mlp",
        {
            "layers": layers,
            "action": {"w": aw.tolist(), "b": ab.tolist(), "act": "identity"},
            "hidden": [layer["b"].__len__() if isinstance(layer["b"], list) else len(layer["b"]) for layer in layers],
        },
    )


def infer(policy: dict, obs: np.ndarray) -> np.ndarray:
    """Deterministic forward pass matching the game runtime."""
    if policy.get("kind") == "heuristic":
        from iron_glove_rl.training.heuristic import heuristic_action

        return heuristic_action(np.asarray(obs, dtype=np.float32))

    x = np.asarray(obs, dtype=np.float64).reshape(-1)
    for layer in policy["layers"]:
        w = np.asarray(layer["w"], dtype=np.float64)
        b = np.asarray(layer["b"], dtype=np.float64)
        x = x @ w.T + b
        if layer.get("act") == "tanh":
            x = np.tanh(x)
    w = np.asarray(policy["action"]["w"], dtype=np.float64)
    b = np.asarray(policy["action"]["b"], dtype=np.float64)
    mean = x @ w.T + b
    yaw = float(np.tanh(mean[0]))
    pitch = float(np.tanh(mean[1]))
    throttle = float(np.tanh(mean[2]))
    fire = float(sigmoid(np.array([mean[3]]))[0])
    return np.array([yaw, pitch, throttle, fire], dtype=np.float32)


def write_policy(policy: dict, json_path: Path = DEFAULT_JSON, ts_path: Path = DEFAULT_TS) -> Path:
    json_path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(policy, separators=(",", ":"))
    json_path.write_text(text + "\n", encoding="utf-8")
    if ts_path:
        ts_path.parent.mkdir(parents=True, exist_ok=True)
        ts_path.write_text(
            "// Generated by iron_glove_rl.utils.export_policy — do not hand-edit.\n"
            f"export const SENTINEL_POLICY_JSON = {json.dumps(text)};\n",
            encoding="utf-8",
        )
    return json_path


def load_policy(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))
