#!/usr/bin/env bash
# Idempotent repository bootstrap for the IRON GLOVE Cloud Agent environment.
# Runs after the repo is checked out. Installs Node dependencies for the client
# and the SpacetimeDB module, installs the SpacetimeDB CLI if missing, and
# materializes client/.env from injected environment secrets.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo "==> Installing client dependencies"
( cd client && npm ci )

echo "==> Installing SpacetimeDB module dependencies"
( cd server && npm ci )

echo "==> Ensuring SpacetimeDB CLI is installed"
export PATH="$HOME/.local/bin:$PATH"
if ! command -v spacetime >/dev/null 2>&1; then
  curl -sSf https://install.spacetimedb.com | sh -s -- --yes
fi
spacetime --version

echo "==> Writing client/.env from environment (git-ignored)"
ENV_FILE="client/.env"
{
  echo "# Generated by .cursor/install.sh from environment secrets. Do not commit."
  if [ -n "${VITE_CESIUM_TOKEN:-}" ]; then
    echo "VITE_CESIUM_TOKEN=${VITE_CESIUM_TOKEN}"
  else
    echo "# VITE_CESIUM_TOKEN not set — add it as a Cloud Agent secret to render the 3D world."
  fi
  if [ -n "${VITE_GOOGLE_MAPS_API_KEY:-}" ]; then
    echo "VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}"
  fi
  echo "VITE_SPACETIMEDB_HOST=${VITE_SPACETIMEDB_HOST:-ws://127.0.0.1:3000}"
  echo "VITE_SPACETIMEDB_DB_NAME=${VITE_SPACETIMEDB_DB_NAME:-iron-glove}"
  if [ -n "${VITE_GROK_API_KEY:-}" ]; then
    echo "VITE_GROK_API_KEY=${VITE_GROK_API_KEY}"
  fi
} > "$ENV_FILE"

echo "==> install complete"
