// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import HitBossReducer from "../hit_boss_reducer";
import JoinReducer from "../join_reducer";
import UpdatePoseReducer from "../update_pose_reducer";

export type HitBossParams = __Infer<typeof HitBossReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type UpdatePoseParams = __Infer<typeof UpdatePoseReducer>;

