// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import JoinGameReducer from "../join_game_reducer";
import UpdateOrientationReducer from "../update_orientation_reducer";

export type JoinGameParams = __Infer<typeof JoinGameReducer>;
export type UpdateOrientationParams = __Infer<typeof UpdateOrientationReducer>;

