// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ApplyDamageReducer from "../apply_damage_reducer";
import DestroySentinelReducer from "../destroy_sentinel_reducer";
import JoinGameReducer from "../join_game_reducer";
import UpdateOrientationReducer from "../update_orientation_reducer";

export type ApplyDamageParams = __Infer<typeof ApplyDamageReducer>;
export type DestroySentinelParams = __Infer<typeof DestroySentinelReducer>;
export type JoinGameParams = __Infer<typeof JoinGameReducer>;
export type UpdateOrientationParams = __Infer<typeof UpdateOrientationReducer>;

