// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Boss = __t.object("Boss", {
  id: __t.u8(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  hp: __t.u8(),
});
export type Boss = __Infer<typeof Boss>;

export const Pilot = __t.object("Pilot", {
  id: __t.identity(),
  name: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  hp: __t.u8(),
  thrusting: __t.bool(),
  alive: __t.bool(),
});
export type Pilot = __Infer<typeof Pilot>;

