// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  missileId: __t.u64().primaryKey().name("missile_id"),
  sentinelId: __t.u32().name("sentinel_id"),
  targetPlayerId: __t.string().name("target_player_id"),
  originX: __t.f64().name("origin_x"),
  originY: __t.f64().name("origin_y"),
  originZ: __t.f64().name("origin_z"),
  velocityX: __t.f32().name("velocity_x"),
  velocityY: __t.f32().name("velocity_y"),
  velocityZ: __t.f32().name("velocity_z"),
  firedAt: __t.timestamp().name("fired_at"),
});
