// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerId: __t.string().primaryKey().name("player_id"),
  positionX: __t.f32().name("position_x"),
  positionY: __t.f32().name("position_y"),
  positionZ: __t.f32().name("position_z"),
  pitch: __t.f32(),
  roll: __t.f32(),
  yaw: __t.f32(),
  suitHealth: __t.f32().name("suit_health"),
  mode: __t.string(),
  isConnected: __t.bool().name("is_connected"),
  updatedAt: __t.timestamp().name("updated_at"),
});
