// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sentinelId: __t.u32().primaryKey().name("sentinel_id"),
  droneType: __t.string().name("drone_type"),
  behavior: __t.string(),
  positionX: __t.f64().name("position_x"),
  positionY: __t.f64().name("position_y"),
  positionZ: __t.f64().name("position_z"),
  velocityX: __t.f32().name("velocity_x"),
  velocityY: __t.f32().name("velocity_y"),
  velocityZ: __t.f32().name("velocity_z"),
  health: __t.f32(),
  targetPlayerId: __t.string().name("target_player_id"),
  patrolIndex: __t.u32().name("patrol_index"),
  lastFiredAt: __t.timestamp().name("last_fired_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
