// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const GameEvent = __t.object("GameEvent", {
  eventId: __t.u64(),
  eventType: __t.string(),
  playerId: __t.string(),
  detail: __t.string(),
  timestamp: __t.timestamp(),
});
export type GameEvent = __Infer<typeof GameEvent>;

export const Missile = __t.object("Missile", {
  missileId: __t.u64(),
  sentinelId: __t.u32(),
  targetPlayerId: __t.string(),
  originX: __t.f64(),
  originY: __t.f64(),
  originZ: __t.f64(),
  velocityX: __t.f32(),
  velocityY: __t.f32(),
  velocityZ: __t.f32(),
  firedAt: __t.timestamp(),
});
export type Missile = __Infer<typeof Missile>;

export const PlayerState = __t.object("PlayerState", {
  playerId: __t.string(),
  positionX: __t.f32(),
  positionY: __t.f32(),
  positionZ: __t.f32(),
  pitch: __t.f32(),
  roll: __t.f32(),
  yaw: __t.f32(),
  suitHealth: __t.f32(),
  mode: __t.string(),
  isConnected: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type PlayerState = __Infer<typeof PlayerState>;

export const SentinelRespawn = __t.object("SentinelRespawn", {
  sentinelId: __t.u32(),
  droneType: __t.string(),
  respawnAt: __t.timestamp(),
});
export type SentinelRespawn = __Infer<typeof SentinelRespawn>;

export const SentinelState = __t.object("SentinelState", {
  sentinelId: __t.u32(),
  droneType: __t.string(),
  behavior: __t.string(),
  positionX: __t.f64(),
  positionY: __t.f64(),
  positionZ: __t.f64(),
  velocityX: __t.f32(),
  velocityY: __t.f32(),
  velocityZ: __t.f32(),
  health: __t.f32(),
  targetPlayerId: __t.string(),
  patrolIndex: __t.u32(),
  lastFiredAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type SentinelState = __Infer<typeof SentinelState>;

export const SentinelTick = __t.object("SentinelTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  idleSince: __t.timestamp(),
});
export type SentinelTick = __Infer<typeof SentinelTick>;

