// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const GameEvent = __t.object("GameEvent", {
  eventId: __t.u64(),
  eventType: __t.string(),
  playerId: __t.string(),
  detail: __t.string(),
  timestamp: __t.timestamp(),
});
export type GameEvent = __Infer<typeof GameEvent>;

export const PlayerState = __t.object("PlayerState", {
  playerId: __t.string(),
  positionX: __t.f32(),
  positionY: __t.f32(),
  positionZ: __t.f32(),
  pitch: __t.f32(),
  roll: __t.f32(),
  yaw: __t.f32(),
  suitHealth: __t.f32(),
  mode: __t.string(),
  isConnected: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type PlayerState = __Infer<typeof PlayerState>;

